//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Transfer {
    
    private string documentNoField;
    
    private string externalDocNoField;
    
    private short documentSourceField;
    
    private string performedByField;
    
    private System.Nullable<System.DateTime> receiveDateField;
    
    private bool receiveDateFieldSpecified;
    
    private string manifestNoField;
    
    private string descriptionField;
    
    private string fromLocationCodeField;
    
    private System.Nullable<short> fromLocationIdField;
    
    private bool fromLocationIdFieldSpecified;
    
    private string toLocationCodeField;
    
    private System.Nullable<short> toLocationIdField;
    
    private bool toLocationIdFieldSpecified;
    
    private string reasonCodeField;
    
    private System.Nullable<short> reasonIdField;
    
    private bool reasonIdFieldSpecified;
    
    private System.Nullable<System.DateTime> beginSendDateField;
    
    private bool beginSendDateFieldSpecified;
    
    private System.Nullable<System.DateTime> endSendDateField;
    
    private bool endSendDateFieldSpecified;
    
    private System.Nullable<System.DateTime> receiveCreateDateField;
    
    private bool receiveCreateDateFieldSpecified;
    
    private string packedByField;
    
    private System.DateTime createDateField;
    
    private bool createDateFieldSpecified;
    
    private System.Nullable<System.DateTime> shipDateField;
    
    private bool shipDateFieldSpecified;
    
    private string billOfLadingField;
    
    private System.Nullable<double> weightField;
    
    private bool weightFieldSpecified;
    
    private System.Nullable<short> numberOfContainersField;
    
    private bool numberOfContainersFieldSpecified;
    
    private short documentStatusField;
    
    private bool documentStatusFieldSpecified;
    
    private string crossRefField;
    
    private bool routedByWarehouseFlagField;
    
    private bool routedByWarehouseFlagFieldSpecified;
    
    private bool receivedByWarehouseFlagField;
    
    private bool receivedByWarehouseFlagFieldSpecified;
    
    private bool shippedByWarehouseFlagField;
    
    private bool shippedByWarehouseFlagFieldSpecified;
    
    private string externalSystemNameField;
    
    private System.Nullable<System.DateTime> lastActivityDateField;
    
    private bool lastActivityDateFieldSpecified;
    
    private string groupingLabelField;
    
    private bool printFlagField;
    
    private bool printFlagFieldSpecified;
    
    private string warehouseCodeField;
    
    private string unitWeightCodeField;
    
    private string shipViaCodeField;
    
    private string carrierCodeField;
    
    private string containerTypeCodeField;
    
    private string inventoryMoveRequestNoField;
    
    private string fromLocationNameField;
    
    private bool fromLocActiveFlagField;
    
    private bool fromLocActiveFlagFieldSpecified;
    
    private bool fromLocUsesOIMFlagField;
    
    private bool fromLocUsesOIMFlagFieldSpecified;
    
    private System.Nullable<sbyte> fromLocRegisterTypeIdField;
    
    private bool fromLocRegisterTypeIdFieldSpecified;
    
    private string fromLocAddressTypeDescField;
    
    private System.Nullable<short> fromLocAddressTypeIdField;
    
    private bool fromLocAddressTypeIdFieldSpecified;
    
    private string fromLocAddressNameField;
    
    private string fromLocAddressLine1Field;
    
    private string fromLocAddressLine2Field;
    
    private string fromLocAddressCityField;
    
    private string fromLocAddressStateField;
    
    private string fromLocAddressZipCodeField;
    
    private string fromLocCountryCodeField;
    
    private string fromLocCountryDescriptionField;
    
    private string toLocationNameField;
    
    private System.Nullable<bool> toLocationActiveFlagField;
    
    private bool toLocationActiveFlagFieldSpecified;
    
    private System.Nullable<bool> toLocationFourWallWHFlagField;
    
    private bool toLocationFourWallWHFlagFieldSpecified;
    
    private System.Nullable<bool> toLocationUsesOIMFlagField;
    
    private bool toLocationUsesOIMFlagFieldSpecified;
    
    private System.Nullable<sbyte> toLocationRegisterTypeIdField;
    
    private bool toLocationRegisterTypeIdFieldSpecified;
    
    private string toLocationAddressTypeDescField;
    
    private System.Nullable<short> toLocationAddressTypeIdField;
    
    private bool toLocationAddressTypeIdFieldSpecified;
    
    private string toLocAddressNameField;
    
    private string toLocAddressLine1Field;
    
    private string toLocAddressLine2Field;
    
    private string toLocAddressCityField;
    
    private string toLocAddressStateField;
    
    private string toLocAddressZipCodeField;
    
    private string toLocCountryCodeField;
    
    private string toLocCountryDescriptionField;
    
    private string warehouseNameField;
    
    private bool warehouseActiveFlagField;
    
    private bool warehouseActiveFlagFieldSpecified;
    
    private string shipViaDescriptionField;
    
    private string carrierNameField;
    
    private string unitWeightLabelField;
    
    private string containerTypeLabelField;
    
    private string inventoryMoveRequestDescField;
    
    private string invMoveReqToLocationCodeField;
    
    private string invMoveReqToLocationNameField;
    
    private System.Nullable<System.DateTime> invMoveReqBeginSendDateField;
    
    private bool invMoveReqBeginSendDateFieldSpecified;
    
    private System.Nullable<System.DateTime> invMoveReqEndSendDateField;
    
    private bool invMoveReqEndSendDateFieldSpecified;
    
    private string invMoveReqGroupingLabelField;
    
    private string invMoveReqReasonCodeField;
    
    private string invMoveReqReasonDescField;
    
    private string reasonDescriptionField;
    
    private bool toCountryEuMemberFlagField;
    
    private bool toCountryEuMemberFlagFieldSpecified;
    
    private bool fromCountryEuMemberFlagField;
    
    private bool fromCountryEuMemberFlagFieldSpecified;
    
    private SKU[] sKUsField;
    
    private Message[] inboundMessagesField;
    
    private Message[] outboundMessagesField;
    
    private decimal idField;
    
    private bool idFieldSpecified;
    
    private short entityActionField;
    
    private bool entityActionFieldSpecified;
    
    private ActionEnum actionField;
    
    private int companyIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DocumentNo {
        get {
            return this.documentNoField;
        }
        set {
            this.documentNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string ExternalDocNo {
        get {
            return this.externalDocNoField;
        }
        set {
            this.externalDocNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public short DocumentSource {
        get {
            return this.documentSourceField;
        }
        set {
            this.documentSourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string PerformedBy {
        get {
            return this.performedByField;
        }
        set {
            this.performedByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<System.DateTime> ReceiveDate {
        get {
            return this.receiveDateField;
        }
        set {
            this.receiveDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReceiveDateSpecified {
        get {
            return this.receiveDateFieldSpecified;
        }
        set {
            this.receiveDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string ManifestNo {
        get {
            return this.manifestNoField;
        }
        set {
            this.manifestNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FromLocationCode {
        get {
            return this.fromLocationCodeField;
        }
        set {
            this.fromLocationCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<short> FromLocationId {
        get {
            return this.fromLocationIdField;
        }
        set {
            this.fromLocationIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FromLocationIdSpecified {
        get {
            return this.fromLocationIdFieldSpecified;
        }
        set {
            this.fromLocationIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ToLocationCode {
        get {
            return this.toLocationCodeField;
        }
        set {
            this.toLocationCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<short> ToLocationId {
        get {
            return this.toLocationIdField;
        }
        set {
            this.toLocationIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ToLocationIdSpecified {
        get {
            return this.toLocationIdFieldSpecified;
        }
        set {
            this.toLocationIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReasonCode {
        get {
            return this.reasonCodeField;
        }
        set {
            this.reasonCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<short> ReasonId {
        get {
            return this.reasonIdField;
        }
        set {
            this.reasonIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReasonIdSpecified {
        get {
            return this.reasonIdFieldSpecified;
        }
        set {
            this.reasonIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<System.DateTime> BeginSendDate {
        get {
            return this.beginSendDateField;
        }
        set {
            this.beginSendDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BeginSendDateSpecified {
        get {
            return this.beginSendDateFieldSpecified;
        }
        set {
            this.beginSendDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<System.DateTime> EndSendDate {
        get {
            return this.endSendDateField;
        }
        set {
            this.endSendDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EndSendDateSpecified {
        get {
            return this.endSendDateFieldSpecified;
        }
        set {
            this.endSendDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<System.DateTime> ReceiveCreateDate {
        get {
            return this.receiveCreateDateField;
        }
        set {
            this.receiveCreateDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReceiveCreateDateSpecified {
        get {
            return this.receiveCreateDateFieldSpecified;
        }
        set {
            this.receiveCreateDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string PackedBy {
        get {
            return this.packedByField;
        }
        set {
            this.packedByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime CreateDate {
        get {
            return this.createDateField;
        }
        set {
            this.createDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CreateDateSpecified {
        get {
            return this.createDateFieldSpecified;
        }
        set {
            this.createDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<System.DateTime> ShipDate {
        get {
            return this.shipDateField;
        }
        set {
            this.shipDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ShipDateSpecified {
        get {
            return this.shipDateFieldSpecified;
        }
        set {
            this.shipDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string BillOfLading {
        get {
            return this.billOfLadingField;
        }
        set {
            this.billOfLadingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<double> Weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WeightSpecified {
        get {
            return this.weightFieldSpecified;
        }
        set {
            this.weightFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<short> NumberOfContainers {
        get {
            return this.numberOfContainersField;
        }
        set {
            this.numberOfContainersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NumberOfContainersSpecified {
        get {
            return this.numberOfContainersFieldSpecified;
        }
        set {
            this.numberOfContainersFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public short DocumentStatus {
        get {
            return this.documentStatusField;
        }
        set {
            this.documentStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DocumentStatusSpecified {
        get {
            return this.documentStatusFieldSpecified;
        }
        set {
            this.documentStatusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string CrossRef {
        get {
            return this.crossRefField;
        }
        set {
            this.crossRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool RoutedByWarehouseFlag {
        get {
            return this.routedByWarehouseFlagField;
        }
        set {
            this.routedByWarehouseFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RoutedByWarehouseFlagSpecified {
        get {
            return this.routedByWarehouseFlagFieldSpecified;
        }
        set {
            this.routedByWarehouseFlagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool ReceivedByWarehouseFlag {
        get {
            return this.receivedByWarehouseFlagField;
        }
        set {
            this.receivedByWarehouseFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReceivedByWarehouseFlagSpecified {
        get {
            return this.receivedByWarehouseFlagFieldSpecified;
        }
        set {
            this.receivedByWarehouseFlagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool ShippedByWarehouseFlag {
        get {
            return this.shippedByWarehouseFlagField;
        }
        set {
            this.shippedByWarehouseFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ShippedByWarehouseFlagSpecified {
        get {
            return this.shippedByWarehouseFlagFieldSpecified;
        }
        set {
            this.shippedByWarehouseFlagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string ExternalSystemName {
        get {
            return this.externalSystemNameField;
        }
        set {
            this.externalSystemNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<System.DateTime> LastActivityDate {
        get {
            return this.lastActivityDateField;
        }
        set {
            this.lastActivityDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LastActivityDateSpecified {
        get {
            return this.lastActivityDateFieldSpecified;
        }
        set {
            this.lastActivityDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string GroupingLabel {
        get {
            return this.groupingLabelField;
        }
        set {
            this.groupingLabelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool PrintFlag {
        get {
            return this.printFlagField;
        }
        set {
            this.printFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PrintFlagSpecified {
        get {
            return this.printFlagFieldSpecified;
        }
        set {
            this.printFlagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string WarehouseCode {
        get {
            return this.warehouseCodeField;
        }
        set {
            this.warehouseCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string UnitWeightCode {
        get {
            return this.unitWeightCodeField;
        }
        set {
            this.unitWeightCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string ShipViaCode {
        get {
            return this.shipViaCodeField;
        }
        set {
            this.shipViaCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string CarrierCode {
        get {
            return this.carrierCodeField;
        }
        set {
            this.carrierCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string ContainerTypeCode {
        get {
            return this.containerTypeCodeField;
        }
        set {
            this.containerTypeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string InventoryMoveRequestNo {
        get {
            return this.inventoryMoveRequestNoField;
        }
        set {
            this.inventoryMoveRequestNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FromLocationName {
        get {
            return this.fromLocationNameField;
        }
        set {
            this.fromLocationNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool FromLocActiveFlag {
        get {
            return this.fromLocActiveFlagField;
        }
        set {
            this.fromLocActiveFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FromLocActiveFlagSpecified {
        get {
            return this.fromLocActiveFlagFieldSpecified;
        }
        set {
            this.fromLocActiveFlagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool FromLocUsesOIMFlag {
        get {
            return this.fromLocUsesOIMFlagField;
        }
        set {
            this.fromLocUsesOIMFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FromLocUsesOIMFlagSpecified {
        get {
            return this.fromLocUsesOIMFlagFieldSpecified;
        }
        set {
            this.fromLocUsesOIMFlagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<sbyte> FromLocRegisterTypeId {
        get {
            return this.fromLocRegisterTypeIdField;
        }
        set {
            this.fromLocRegisterTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FromLocRegisterTypeIdSpecified {
        get {
            return this.fromLocRegisterTypeIdFieldSpecified;
        }
        set {
            this.fromLocRegisterTypeIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string FromLocAddressTypeDesc {
        get {
            return this.fromLocAddressTypeDescField;
        }
        set {
            this.fromLocAddressTypeDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<short> FromLocAddressTypeId {
        get {
            return this.fromLocAddressTypeIdField;
        }
        set {
            this.fromLocAddressTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FromLocAddressTypeIdSpecified {
        get {
            return this.fromLocAddressTypeIdFieldSpecified;
        }
        set {
            this.fromLocAddressTypeIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string FromLocAddressName {
        get {
            return this.fromLocAddressNameField;
        }
        set {
            this.fromLocAddressNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string FromLocAddressLine1 {
        get {
            return this.fromLocAddressLine1Field;
        }
        set {
            this.fromLocAddressLine1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string FromLocAddressLine2 {
        get {
            return this.fromLocAddressLine2Field;
        }
        set {
            this.fromLocAddressLine2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string FromLocAddressCity {
        get {
            return this.fromLocAddressCityField;
        }
        set {
            this.fromLocAddressCityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string FromLocAddressState {
        get {
            return this.fromLocAddressStateField;
        }
        set {
            this.fromLocAddressStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string FromLocAddressZipCode {
        get {
            return this.fromLocAddressZipCodeField;
        }
        set {
            this.fromLocAddressZipCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string FromLocCountryCode {
        get {
            return this.fromLocCountryCodeField;
        }
        set {
            this.fromLocCountryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string FromLocCountryDescription {
        get {
            return this.fromLocCountryDescriptionField;
        }
        set {
            this.fromLocCountryDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string ToLocationName {
        get {
            return this.toLocationNameField;
        }
        set {
            this.toLocationNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<bool> ToLocationActiveFlag {
        get {
            return this.toLocationActiveFlagField;
        }
        set {
            this.toLocationActiveFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ToLocationActiveFlagSpecified {
        get {
            return this.toLocationActiveFlagFieldSpecified;
        }
        set {
            this.toLocationActiveFlagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<bool> ToLocationFourWallWHFlag {
        get {
            return this.toLocationFourWallWHFlagField;
        }
        set {
            this.toLocationFourWallWHFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ToLocationFourWallWHFlagSpecified {
        get {
            return this.toLocationFourWallWHFlagFieldSpecified;
        }
        set {
            this.toLocationFourWallWHFlagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<bool> ToLocationUsesOIMFlag {
        get {
            return this.toLocationUsesOIMFlagField;
        }
        set {
            this.toLocationUsesOIMFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ToLocationUsesOIMFlagSpecified {
        get {
            return this.toLocationUsesOIMFlagFieldSpecified;
        }
        set {
            this.toLocationUsesOIMFlagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<sbyte> ToLocationRegisterTypeId {
        get {
            return this.toLocationRegisterTypeIdField;
        }
        set {
            this.toLocationRegisterTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ToLocationRegisterTypeIdSpecified {
        get {
            return this.toLocationRegisterTypeIdFieldSpecified;
        }
        set {
            this.toLocationRegisterTypeIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string ToLocationAddressTypeDesc {
        get {
            return this.toLocationAddressTypeDescField;
        }
        set {
            this.toLocationAddressTypeDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<short> ToLocationAddressTypeId {
        get {
            return this.toLocationAddressTypeIdField;
        }
        set {
            this.toLocationAddressTypeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ToLocationAddressTypeIdSpecified {
        get {
            return this.toLocationAddressTypeIdFieldSpecified;
        }
        set {
            this.toLocationAddressTypeIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string ToLocAddressName {
        get {
            return this.toLocAddressNameField;
        }
        set {
            this.toLocAddressNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string ToLocAddressLine1 {
        get {
            return this.toLocAddressLine1Field;
        }
        set {
            this.toLocAddressLine1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string ToLocAddressLine2 {
        get {
            return this.toLocAddressLine2Field;
        }
        set {
            this.toLocAddressLine2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string ToLocAddressCity {
        get {
            return this.toLocAddressCityField;
        }
        set {
            this.toLocAddressCityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string ToLocAddressState {
        get {
            return this.toLocAddressStateField;
        }
        set {
            this.toLocAddressStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string ToLocAddressZipCode {
        get {
            return this.toLocAddressZipCodeField;
        }
        set {
            this.toLocAddressZipCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string ToLocCountryCode {
        get {
            return this.toLocCountryCodeField;
        }
        set {
            this.toLocCountryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string ToLocCountryDescription {
        get {
            return this.toLocCountryDescriptionField;
        }
        set {
            this.toLocCountryDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string WarehouseName {
        get {
            return this.warehouseNameField;
        }
        set {
            this.warehouseNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool WarehouseActiveFlag {
        get {
            return this.warehouseActiveFlagField;
        }
        set {
            this.warehouseActiveFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool WarehouseActiveFlagSpecified {
        get {
            return this.warehouseActiveFlagFieldSpecified;
        }
        set {
            this.warehouseActiveFlagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string ShipViaDescription {
        get {
            return this.shipViaDescriptionField;
        }
        set {
            this.shipViaDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string CarrierName {
        get {
            return this.carrierNameField;
        }
        set {
            this.carrierNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string UnitWeightLabel {
        get {
            return this.unitWeightLabelField;
        }
        set {
            this.unitWeightLabelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string ContainerTypeLabel {
        get {
            return this.containerTypeLabelField;
        }
        set {
            this.containerTypeLabelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string InventoryMoveRequestDesc {
        get {
            return this.inventoryMoveRequestDescField;
        }
        set {
            this.inventoryMoveRequestDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string InvMoveReqToLocationCode {
        get {
            return this.invMoveReqToLocationCodeField;
        }
        set {
            this.invMoveReqToLocationCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string InvMoveReqToLocationName {
        get {
            return this.invMoveReqToLocationNameField;
        }
        set {
            this.invMoveReqToLocationNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<System.DateTime> InvMoveReqBeginSendDate {
        get {
            return this.invMoveReqBeginSendDateField;
        }
        set {
            this.invMoveReqBeginSendDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InvMoveReqBeginSendDateSpecified {
        get {
            return this.invMoveReqBeginSendDateFieldSpecified;
        }
        set {
            this.invMoveReqBeginSendDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<System.DateTime> InvMoveReqEndSendDate {
        get {
            return this.invMoveReqEndSendDateField;
        }
        set {
            this.invMoveReqEndSendDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool InvMoveReqEndSendDateSpecified {
        get {
            return this.invMoveReqEndSendDateFieldSpecified;
        }
        set {
            this.invMoveReqEndSendDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string InvMoveReqGroupingLabel {
        get {
            return this.invMoveReqGroupingLabelField;
        }
        set {
            this.invMoveReqGroupingLabelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string InvMoveReqReasonCode {
        get {
            return this.invMoveReqReasonCodeField;
        }
        set {
            this.invMoveReqReasonCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string InvMoveReqReasonDesc {
        get {
            return this.invMoveReqReasonDescField;
        }
        set {
            this.invMoveReqReasonDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReasonDescription {
        get {
            return this.reasonDescriptionField;
        }
        set {
            this.reasonDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool ToCountryEuMemberFlag {
        get {
            return this.toCountryEuMemberFlagField;
        }
        set {
            this.toCountryEuMemberFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ToCountryEuMemberFlagSpecified {
        get {
            return this.toCountryEuMemberFlagFieldSpecified;
        }
        set {
            this.toCountryEuMemberFlagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool FromCountryEuMemberFlag {
        get {
            return this.fromCountryEuMemberFlagField;
        }
        set {
            this.fromCountryEuMemberFlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool FromCountryEuMemberFlagSpecified {
        get {
            return this.fromCountryEuMemberFlagFieldSpecified;
        }
        set {
            this.fromCountryEuMemberFlagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("SKU", IsNullable=false)]
    public SKU[] SKUs {
        get {
            return this.sKUsField;
        }
        set {
            this.sKUsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Message", IsNullable=false)]
    public Message[] InboundMessages {
        get {
            return this.inboundMessagesField;
        }
        set {
            this.inboundMessagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Message", IsNullable=false)]
    public Message[] OutboundMessages {
        get {
            return this.outboundMessagesField;
        }
        set {
            this.outboundMessagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IdSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public short EntityAction {
        get {
            return this.entityActionField;
        }
        set {
            this.entityActionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EntityActionSpecified {
        get {
            return this.entityActionFieldSpecified;
        }
        set {
            this.entityActionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ActionEnum Action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int CompanyId {
        get {
            return this.companyIdField;
        }
        set {
            this.companyIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class SKU {
    
    private string styleCodeField;
    
    private System.Nullable<decimal> styleIdField;
    
    private bool styleIdFieldSpecified;
    
    private string colorCodeField;
    
    private System.Nullable<short> colorIdField;
    
    private bool colorIdFieldSpecified;
    
    private string primarySizeLabelField;
    
    private string secondarySizeLabelField;
    
    private System.Nullable<double> sKUIdField;
    
    private bool sKUIdFieldSpecified;
    
    private string cartonNoField;
    
    private System.Nullable<int> unitsReceivedField;
    
    private bool unitsReceivedFieldSpecified;
    
    private string uPCNoField;
    
    private string reasonCodeField;
    
    private System.Nullable<short> reasonIdField;
    
    private bool reasonIdFieldSpecified;
    
    private System.Nullable<int> unitsSentField;
    
    private bool unitsSentFieldSpecified;
    
    private decimal idField;
    
    private bool idFieldSpecified;
    
    private ActionEnum actionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string StyleCode {
        get {
            return this.styleCodeField;
        }
        set {
            this.styleCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<decimal> StyleId {
        get {
            return this.styleIdField;
        }
        set {
            this.styleIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StyleIdSpecified {
        get {
            return this.styleIdFieldSpecified;
        }
        set {
            this.styleIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string ColorCode {
        get {
            return this.colorCodeField;
        }
        set {
            this.colorCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<short> ColorId {
        get {
            return this.colorIdField;
        }
        set {
            this.colorIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ColorIdSpecified {
        get {
            return this.colorIdFieldSpecified;
        }
        set {
            this.colorIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string PrimarySizeLabel {
        get {
            return this.primarySizeLabelField;
        }
        set {
            this.primarySizeLabelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string SecondarySizeLabel {
        get {
            return this.secondarySizeLabelField;
        }
        set {
            this.secondarySizeLabelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<double> SKUId {
        get {
            return this.sKUIdField;
        }
        set {
            this.sKUIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SKUIdSpecified {
        get {
            return this.sKUIdFieldSpecified;
        }
        set {
            this.sKUIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string CartonNo {
        get {
            return this.cartonNoField;
        }
        set {
            this.cartonNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<int> UnitsReceived {
        get {
            return this.unitsReceivedField;
        }
        set {
            this.unitsReceivedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnitsReceivedSpecified {
        get {
            return this.unitsReceivedFieldSpecified;
        }
        set {
            this.unitsReceivedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string UPCNo {
        get {
            return this.uPCNoField;
        }
        set {
            this.uPCNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ReasonCode {
        get {
            return this.reasonCodeField;
        }
        set {
            this.reasonCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<short> ReasonId {
        get {
            return this.reasonIdField;
        }
        set {
            this.reasonIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReasonIdSpecified {
        get {
            return this.reasonIdFieldSpecified;
        }
        set {
            this.reasonIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<int> UnitsSent {
        get {
            return this.unitsSentField;
        }
        set {
            this.unitsSentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnitsSentSpecified {
        get {
            return this.unitsSentFieldSpecified;
        }
        set {
            this.unitsSentFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IdSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ActionEnum Action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
public enum ActionEnum {
    
    /// <remarks/>
    unchanged,
    
    /// <remarks/>
    add,
    
    /// <remarks/>
    delete,
    
    /// <remarks/>
    update,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Message {
    
    private string messageTypeDescriptionField;
    
    private string messageTextField;
    
    private short messagTypeMaxLenField;
    
    private bool messagTypeMaxLenFieldSpecified;
    
    private bool messageTypeExclusiveField;
    
    private bool messageTypeExclusiveFieldSpecified;
    
    private System.Nullable<short> messageTranTypeField;
    
    private bool messageTranTypeFieldSpecified;
    
    private decimal idField;
    
    private bool idFieldSpecified;
    
    private ActionEnum actionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MessageTypeDescription {
        get {
            return this.messageTypeDescriptionField;
        }
        set {
            this.messageTypeDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MessageText {
        get {
            return this.messageTextField;
        }
        set {
            this.messageTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public short MessagTypeMaxLen {
        get {
            return this.messagTypeMaxLenField;
        }
        set {
            this.messagTypeMaxLenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MessagTypeMaxLenSpecified {
        get {
            return this.messagTypeMaxLenFieldSpecified;
        }
        set {
            this.messagTypeMaxLenFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool MessageTypeExclusive {
        get {
            return this.messageTypeExclusiveField;
        }
        set {
            this.messageTypeExclusiveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MessageTypeExclusiveSpecified {
        get {
            return this.messageTypeExclusiveFieldSpecified;
        }
        set {
            this.messageTypeExclusiveFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public System.Nullable<short> MessageTranType {
        get {
            return this.messageTranTypeField;
        }
        set {
            this.messageTranTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MessageTranTypeSpecified {
        get {
            return this.messageTranTypeFieldSpecified;
        }
        set {
            this.messageTranTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IdSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ActionEnum Action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class SKUs {
    
    private SKU[] sKUField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SKU")]
    public SKU[] SKU {
        get {
            return this.sKUField;
        }
        set {
            this.sKUField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class InboundMessages {
    
    private Message[] messageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Message")]
    public Message[] Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class OutboundMessages {
    
    private Message[] messageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Message")]
    public Message[] Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
}
